name: Chakra UI React Track Latest Version

on:
  workflow_dispatch: # Manual testing
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches:
      - main
      - feature/chakra-version-watch

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - name: Get Yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Checkout
        uses: actions/checkout@master

      - name: Enable node
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Load Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump @chakra-ui/react if newer available
        run: yarn bump-version

      - name: Commit package.json
        run: |
          git add package.json
          git add yarn.lock
          git diff --staged --quiet || git commit -m "chore(package.json): $GITHUB_SHA"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          title: Bump Chakra UI React version to latest
          branch: chore/chakra-version-bump
